# Generated by Django 3.2.23 on 2023-12-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
