# Generated by Django 3.2.23 on 2023-12-13 11:38

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=TjPFZaMe2yw'),
        ),
    ]
