# Generated by Django 3.2.23 on 2023-12-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
