# Generated by Django 3.2.23 on 2023-12-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
